<?php

return [
    'districts' => [
		'বাগেরহাট'=>1,'বান্দরবান'=>2,'বরগুনা'=>3,'ব্রাহ্মণবাড়িয়া'=>5,'ভোলা'=>6,
		'বগুড়া'=>7,'চাঁদপুর'=>8,'চাঁপাইনবাবগঞ্জ'=>9,'চুয়াডাঙ্গা'=>11,'কক্সবাজার'=>12,
		'ঢাকা'=>14,'দিনাজপুর'=>15,'ফরিদপুর'=>16,'ফেনী'=>17,'গাইবান্ধা'=>18,'গাজীপুর'=>19,
		'গোপালগঞ্জ'=>20,'হবিগঞ্জ'=>21,'জামালপুর'=>22,'ঝালকাঠি'=>24,'ঝিনাইদহ'=>25,
		'জয়পুরহাট'=>26,'খাগড়াছড়ি'=>27,'খুলনা'=>28,'কিশোরগঞ্জ'=>29,'কুড়িগ্রাম'=>30,
		'কুষ্টিয়া'=>31,'লক্ষ্মীপুর'=>32,'লালমনিরহাট'=>33,'মাদারীপুর'=>34,'মাগুরা'=>35,
		'মানিকগঞ্জ'=>36,'মেহেরপুর'=>37,'মৌলভীবাজার'=>38,'মুন্সিগঞ্জ'=>39,'ময়মনসিংহ'=>40,
		'নওগাঁ'=>41,'নড়াইল'=>42,'নারায়ণগঞ্জ'=>43,'নাটোর'=>45,'নেত্রকোনা'=>46,
		'নীলফামারী'=>47,'নোয়াখালী'=>48,'পাবনা'=>49,'পঞ্চগড়'=>50,'পটুয়াখালী'=>51,
		'পিরোজপুর'=>52,'রাজবাড়ী'=>53,'রাজশাহী'=>54,'রাঙ্গামাটি'=>55,'রংপুর'=>56,
		'সাতক্ষীরা'=>57,'শরীয়তপুর'=>58,'শেরপুর'=>59,'সিরাজগঞ্জ'=>60,'সুনামগঞ্জ'=>61,
		'সিলেট'=>62,'টাঙ্গাইল'=>63,'ঠাকুরগাঁও'=>64,
		'chattogram' => 10,
		'চট্টগ্রাম' => 10,
		'চিটাগং' => 10,
		'barishal' => 4,
		'বরিশাল' => 4,
		'narsingdi' => 44,
		'narsingdhi' => 44,
		'narshingdi' => 44,
		'নরসিংদী' => 44,
		'comilla' => 13,
		'কুমিল্লা' => 13,
		'jessore' => 23,
		'যশোর' => 23,
		'bogra' => 7,
		'বগুড়া' => 7,
        'ঢাকা' => 14,
        'বরগুনা' => 3,
        'গাজীপুর' => 19,
    ],

    'upazilas' => [
		'মিরপুর ১০' => [81],
		'মিরপুর ১১' => [81],
		'হালিশহর' => [261],
        'halishohor' => [261],
        'halishohar' => [261],
        'halishahar' => [261],
        'তুরাগ' => [142],
        'মিরপুর ১০' => [81],
        'মোহাম্মদপুর' => [94, 562],
        'সাভার' => [122],
        'কেরানীগঞ্জ' => [67],
    ],

    // Verified proper-name translations used by the generic structured-title engine.
    'structured_bases' => [
        'uttara' => ['উত্তরা'],
    ],

    'localities' => [
		'nathullabad' => ['upazila_id' => 192, 'requires_district_id' => 4],
		'natullahbad' => ['upazila_id' => 192, 'requires_district_id' => 4],
		'natullabad' => ['upazila_id' => 192, 'requires_district_id' => 4],
		'notullabad' => ['upazila_id' => 192, 'requires_district_id' => 4],
		'নথুল্লাবাদ' => ['upazila_id' => 192, 'requires_district_id' => 4],
		'satirpara' => ['upazila_id' => 475, 'requires_district_id' => 44],
		'satir para' => ['upazila_id' => 475, 'requires_district_id' => 44],
		'সাটিরপাড়া' => ['upazila_id' => 475, 'requires_district_id' => 44],
        'dharangartek' => ['upazila_id' => 142, 'union_id' => 1955],
        'dharangertek' => ['upazila_id' => 142, 'union_id' => 1955],
        'ধরঙ্গারটেক' => ['upazila_id' => 142, 'union_id' => 1955],
        'আমতলী' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'টঙ্গি' => ['upazila_id' => 371],
        'টঙ্গী' => ['upazila_id' => 371],
        'amtali' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'amtoli' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'amtoly' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'gozkhali' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'gojkhali' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'goz khali' => ['upazila_id' => 181, 'requires_district_id' => 3],
        'goj khali' => ['upazila_id' => 181, 'requires_district_id' => 3],
    ],
];
